# Generated by Django 3.2.7 on 2021-09-26 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitgraphql', '0002_customer_response_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='response_data',
        ),
    ]
